name: epionesante
description: Epione Santé

publish_to: 'none'
version: 1.1.48+48

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
      sdk: flutter

  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.13
  path_provider: ^2.0.9
  package_info_plus: ^4.0.2
  sqflite: ^2.3.0
  intl: ^0.18.0
  path: ^1.8.0
  http: ^0.13.4
  uuid: ^3.0.6

  firebase_core: ^2.16.0
  firebase_messaging: ^14.6.8
  firebase_messaging_platform_interface: ^4.5.7

  url_launcher: ^6.1.14

  flutter_email_sender: ^5.1.0
  toggle_switch: ^2.0.1
  age_calculator: ^1.0.0
  flutter_spinkit: ^5.1.0
  flutter_sms: ^2.3.3
  syncfusion_flutter_charts: ^20.2.36
  cached_network_image: ^3.2.1

  flutter_multiselect: ^1.0.0
#  chips_choice_null_safety: ^2.0.6

  azlistview:

  flutter_html: ^3.0.0-beta.2
  scrollable_positioned_list: ^0.2.3
  keyboard_actions: ^4.0.1
  flutter_time_picker_spinner: ^2.0.0

  gradient_colored_slider: ^1.0.2
  badges: ^2.0.3
  syncfusion_flutter_xlsio: ^20.3.47-beta
  file_saver: ^0.1.1
  file: ^6.1.4
  syncfusion_flutter_sliders: ^20.3.58
  flutter_app_badger: ^1.5.0
  webview_flutter: ^4.4.1


flutter:
  uses-material-design: true
  assets:
    - assets/images/


